version: '3.9'
services:
  track-service:
    image: track_image
    container_name: track-service
    build: BEJ_C2_S3_REST_API_MONGODB_MC_1
    restart: always
    networks:
      - mynetwork
    ports:
      - 8087:8087
    depends_on:
      - mongoService


  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    networks:
      - mynetwork

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: UserAuthentication
    restart: always
    networks:
      - mynetwork
    ports:
      - 8088:8088
    depends_on:
      - mysqlService


  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"



networks:
  mynetwork:
    driver: bridge